
language: cpp

os: linux
dist: xenial
sudo: false

notifications:
  email: false

git:
  submodules: true

matrix:
  include:
    # OSX Clang
    - env: COMPILER=clang++ BUILD_TYPE=Debug
      os: osx
      osx_image: xcode10.2
    - env: COMPILER=clang++ BUILD_TYPE=Release
      os: osx
      osx_image: xcode10.2

    # OSX GCC 8 
    - env: COMPILER=g++-8 BUILD_TYPE=Debug MATRIX_EVAL="brew install gcc@8"
      os: osx
      osx_image: xcode10.2
    - env: COMPILER=g++-8 BUILD_TYPE=Release MATRIX_EVAL="brew install gcc@8"
      os: osx
      osx_image: xcode10.2

    # Linux Clang 7
    - env: COMPILER=clang++-7 BUILD_TYPE=Debug
      addons: &clang7
        apt:
          packages:
            - clang-7
            - libstdc++-8-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-7

    - env: COMPILER=clang++-7 BUILD_TYPE=Release
      addons: *clang7

    # Linux GCC 8
    - env: COMPILER=g++-8 BUILD_TYPE=Debug
      addons: &gcc8
        apt:
          packages:
            - g++-8
          sources:
            - ubuntu-toolchain-r-test
    - env: COMPILER=g++-8 BUILD_TYPE=Release
      addons: *gcc8

before_install:
  - eval ${MATRIX_EVAL}
  - export CXX=${COMPILER}
  - ${CXX} --version
  - cmake --version

before_script:
  - cd "${TRAVIS_BUILD_DIR}"
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE}

script:
  - cmake --build . -- -j2 
  - ctest --output-on-failure -j2

