
language: cpp

os: linux
dist: trusty
sudo: false

notifications:
  email: false

git:
  submodules: true

matrix:
  include:
    # OSX Clang
    #- env: COMPILER=clang++ BUILD_TYPE=Debug
    #  os: osx
    #  osx_image: xcode9.3beta
    #  compiler: clang
    #- env: COMPILER=clang++ BUILD_TYPE=Release
    #  os: osx
    #  osx_image: xcode9.3beta
    #  compiler: clang

    # OSX GCC 7 
    - env: COMPILER=g++-7 BUILD_TYPE=Debug MATRIX_EVAL="brew cask uninstall oclint && brew install gcc@7"
      os: osx
      osx_image: xcode9.3beta
    - env: COMPILER=g++-7 BUILD_TYPE=Release MATRIX_EVAL="brew cask uninstall oclint && brew install gcc@7"
      os: osx
      osx_image: xcode9.3beta

    # Linux Clang 5.0
    - env: COMPILER=clang++-5.0 BUILD_TYPE=Debug
      addons: &clang50
        apt:
          packages:
            - clang-5.0
            - libstdc++-7-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
    - env: COMPILER=clang++-5.0 BUILD_TYPE=Release
      addons: *clang50

    # Linux GCC 7
    - env: COMPILER=g++-7 BUILD_TYPE=Debug
      addons: &gcc70
        apt:
          packages:
            - g++-7
          sources:
            - ubuntu-toolchain-r-test
    - env: COMPILER=g++-7 BUILD_TYPE=Release
      addons: *gcc70

before_install:
  - eval ${MATRIX_EVAL}
  - export CXX=${COMPILER}
  - ${CXX} --version
  - cmake --version

before_script:
  - cd "${TRAVIS_BUILD_DIR}"
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE}

script:
  - cmake --build . -- -j2 
  - ctest --output-on-failure -j2

