
clone_depth: 50

image:
  - Visual Studio 2017

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

install:
  - git submodule update --init --recursive

before_build:
  - ps: |
      mkdir build
      cd build
      if ($env:PLATFORM -eq "x64") {
          cmake .. -G "Visual Studio 15 2017 Win64"
      } else {
          cmake .. -G "Visual Studio 15 2017"
      }

build_script:
  - cmake --build . --config %CONFIGURATION% -- /m:2 /v:minimal

test_script:
  - ctest -C %CONFIGURATION% --output-on-failure -j2

deploy: off

